"""добавил таблицы для ai и новые поля ключей

Revision ID: 106270e80c55
Revises: 996e4bdf0928
Create Date: 2026-02-16 22:08:12.738959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106270e80c55'
down_revision: Union[str, None] = '996e4bdf0928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_api_keys', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_api_keys', 'is_active')
    # ### end Alembic commands ###
