"""Создал Chat, к которому привязаны сообщения и вынес в него из сообщений user_id и product_id

Revision ID: 24c1a965f515
Revises: 2b16fb6f991e
Create Date: 2026-02-18 23:52:46.342944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c1a965f515'
down_revision: Union[str, None] = '2b16fb6f991e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ai_configs', sa.Column('is_stream', sa.Boolean(), nullable=False))
    op.add_column('ai_configs', sa.Column('is_json', sa.Boolean(), nullable=False))
    op.add_column('chat_messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('chat_messages_product_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_user_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'user_id')
    op.drop_column('chat_messages', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_user_id_fkey'), 'chat_messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('chat_messages_product_id_fkey'), 'chat_messages', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'chat_id')
    op.drop_column('ai_configs', 'is_json')
    op.drop_column('ai_configs', 'is_stream')
    op.drop_table('chats')
    # ### end Alembic commands ###
