"""Связи продукта (ondelete='CASCADE')

Revision ID: 2b16fb6f991e
Revises: 9c6903e6249c
Create Date: 2026-02-17 22:36:17.057335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b16fb6f991e'
down_revision: Union[str, None] = '9c6903e6249c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_summaries_product_id_fkey'), 'ai_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'ai_summaries', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chat_messages_product_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('product_metrics_product_id_fkey'), 'product_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'product_metrics', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reviews_product_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_product_id_fkey'), 'reviews', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('product_metrics_product_id_fkey'), 'product_metrics', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_product_id_fkey'), 'chat_messages', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'ai_summaries', type_='foreignkey')
    op.create_foreign_key(op.f('ai_summaries_product_id_fkey'), 'ai_summaries', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
