"""UserUsage

Revision ID: 310bf5dc94aa
Revises: 5e06c1de6228
Create Date: 2026-02-25 00:30:04.363677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310bf5dc94aa'
down_revision: Union[str, None] = '5e06c1de6228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('analysis_count', sa.Integer(), nullable=False),
    sa.Column('chat_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='idx_user_usage_date')
    )
    op.add_column('ranks', sa.Column('daily_analysis_limit', sa.Integer(), nullable=True))
    op.add_column('ranks', sa.Column('daily_chat_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ranks', 'daily_chat_limit')
    op.drop_column('ranks', 'daily_analysis_limit')
    op.drop_table('user_usage')
    # ### end Alembic commands ###
