"""каскад делит для моделей

Revision ID: 3da58c51e22a
Revises: 24c1a965f515
Create Date: 2026-02-19 00:06:17.754784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da58c51e22a'
down_revision: Union[str, None] = '24c1a965f515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('system_ai_models_api_key_id_fkey'), 'system_ai_models', type_='foreignkey')
    op.create_foreign_key(None, 'system_ai_models', 'system_ai_api_keys', ['api_key_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_ai_models', type_='foreignkey')
    op.create_foreign_key(op.f('system_ai_models_api_key_id_fkey'), 'system_ai_models', 'system_ai_api_keys', ['api_key_id'], ['id'])
    # ### end Alembic commands ###
