"""настроил названия в user

Revision ID: 48d4ddd61e0c
Revises: 4c5a9e8d9011
Create Date: 2026-02-23 23:29:28.143820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d4ddd61e0c'
down_revision: Union[str, None] = '4c5a9e8d9011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'worker_id')
    # ### end Alembic commands ###
