"""обновил связи продукта и чатс

Revision ID: 4c5a9e8d9011
Revises: 3da58c51e22a
Create Date: 2026-02-19 00:14:02.258678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5a9e8d9011'
down_revision: Union[str, None] = '3da58c51e22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
