"""Переход на gemini embeddings


Revision ID: 7da5b6c9cc8e
Revises: 6b7c99277281
Create Date: 2026-05-13 16:26:33.747677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7da5b6c9cc8e'
down_revision: Union[str, None] = '6b7c99277281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Очищаем старые эмбеддинги, так как они несовместимы с новой моделью
    op.execute("UPDATE metrics SET embedding = NULL WHERE embedding IS NOT NULL")
    
    # Изменяем размерность векторного поля
    op.alter_column('metrics', 'embedding',
               existing_type=Vector(4096),
               type_=Vector(3072),
               existing_nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrics', 'embedding',
               existing_type=Vector(3072),
               type_=Vector(4096),
               existing_nullable=True)
    # ### end Alembic commands ###
