"""add raw_content

Revision ID: 996e4bdf0928
Revises: 7c0b03e7f0b9
Create Date: 2026-02-16 01:50:49.141384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996e4bdf0928'
down_revision: Union[str, None] = '7c0b03e7f0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('raw_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'raw_content')
    # ### end Alembic commands ###
